test: add spaces new tests
D3PSI/lumium pull request #165
Opened 2022-12-07 11:03 UTC by ReddixT

test: add spaces creat and join files

2022-12-07 14:11 UTC, D3PSI approved these changes

2022-12-10 11:26 UTC, theArgex submitted a review, later dismissed

2022-12-12 20:09 UTC, D3PSI commented
@ReddixT can this PR be merged?

2022-12-12 20:17 UTC, ReddixT commented
> @ReddixT can this PR be merged?

no not yet, not all tests are implemented yet

2022-12-14 21:26 UTC, D3PSI requested changes
please add `cypress/downloads` to `.gitignore` and remove the files already in the git tree. thanks :)

2022-12-14 21:30 UTC, D3PSI approved these changes

2022-12-14 21:38 UTC, merged